### ISSUE TITLE
Documentation on how to host multiple servers on the same machine

### ISSUE THREAD

**Issue by YuxuanChen** [Jamesits/docker-dst-server#10]
It was easy enough to get this container to work for one server, but I would like to be able to host multiple servers on the same machine. How difficult would it be to support this?

**Comment by Jamesits** [comment]
As far as I can tell currently:

### If you don't need caves server

run multiple instances of this container, expose port 10999 to different external ports, and let users connect using `c_connect("IP address", port[, "password"])`.

### If you need caves server and have multiple IP addresses bonded to your server

you can expose ports on different IPs. See https://docs.docker.com/config/containers/container-networking/#published-ports

### If you need caves server and have to reuse the only IP address on your server

1. Run the container once per server to generate default config: `docker run -v ~/dst/server_1:/data  -it jamesits/dst-server:latest`
1. Open `~/dst/server_1/DoNotStarveTogether/Cluster_1/Master/server.ini`, change `server_port` (e.g. 20000)
1. Open `~/dst/server_1/DoNotStarveTogether/Cluster_1/Caves/server.ini`, change `server_port` (e.g. 20001)
1. Run the container again and expose the new ports: `docker run -v ~/dst/server_1:/data -p 20000-20001:20000-20001/udp -it jamesits/dst-server:latest`
1. Let user connect to the new port, e.g.: `c_connect("192.0.2.2", 20000, "password)` in the game console

Steam discovery (global catalog search in the game) will likely to fail but your mileage may vary. 

I haven't tried this configuration, if you have experiment results please share with me in this thread. Thanks.

**Comment by YuxuanChen** [comment]
I'm in the third case: I only have 1 IP address and I need 2 worlds:

World1Master
World1Caves

World2Master
World2Caves

I got World1Master and World1Caves working only. I copied the World2 settings into the World1 data folder as Cluster_2, is that correct? So now, my data folder looks like this:

ls ~/.klei/DoNotStarveTogether/DoNotStarveTogether:
Cluster_1
Cluster_2

I changed Cluster_2/Master/server.ini: server_port -> 20000
I changed Cluster_2/Caves/server.ini: server_port -> 20001

Using docker-compose, I exposed these ports as well: 20000-20001:20000-20001.

I ran c_connect("192.168.1.x", 20000, "password") but it doesn't work: Server is not responding. (It works when I am trying to connect to Cluster_1)

Do I need to change master_port in cluster.ini, or master_server_port in Cluster_2/Master/server.ini?

Thanks,
Yuxuan
Feb 22, 2019, 2:09 AM by notifications@github.com:

**Comment by Jamesits** [comment]
No, you should copy your inner `DoNotStarveTogether` directory to another place rather than creating `Cluster_2`. 

Like I've stated, if you need to run 2 different servers, you should map 2 different directories to `/data` for 2 containers:

```
docker run -v ~/dst/server_1:/data ...
docker run -v ~/dst/server_2:/data ...
```

The directory structure will look like:

```
.
├───server_1
│   └───DoNotStarveTogether
│       └───Cluster_1
│           ├───Caves
│           └───Master
└───server_2
    └───DoNotStarveTogether
        └───Cluster_1
            ├───Caves
            └───Master
```

**Comment by YuxuanChen** [comment]
Ahh I see, does this mean I need to run two instances of the docker container?

Feb 22, 2019, 10:21 PM by notifications@github.com:

**Comment by Jamesits** [comment]
Yes

**Comment by YuxuanChen** [comment]
Thanks a lot for your help! Here is the docker-compose file that I used to get my servers up and running simultaneously (it's confirmed to work for me):

```
version: "3"
services:
  dst-server-1:
    container_name: dst-server-1
    image: jamesits/dst-server:latest
    deploy:
        restart_policy:
            condition: always
    ports:
        - "10999-11000:10999-11000/udp"
        - "12346-12347:12346-12347/udp"
    volumes:
        - ~/.klei_1/DoNotStarveTogether:/data
    stop_grace_period: 2m

  # dst-server-2:
  #   container_name: dst-server-2
  #   image: jamesits/dst-server:latest
  #   deploy:
  #       restart_policy:
  #           condition: always
  #   ports:
  #       - "20999-21000:20999-21000/udp"
  #       - "22346-22347:22346-22347/udp"
  #   volumes:
  #       - ~/.klei_2/DoNotStarveTogether:/data
  #   stop_grace_period: 2m
```
